# Generated by Django 3.2.7 on 2021-09-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True, verbose_name='Titulo')),
                ('cantor', models.CharField(blank=True, max_length=63, null=True, verbose_name='Cantor')),
                ('musica', models.FileField(help_text='Adicione aqui musicas no formato .mp3', null=True, upload_to='musics/', verbose_name='Musica')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musicas',
            },
        ),
    ]
