# Generated by Django 3.2.7 on 2021-09-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Adicione um titulo que descreve sua playlist', max_length=255, null=True, verbose_name='Titulo')),
                ('musicas', models.ManyToManyField(to='display.Musica', verbose_name='Músicas')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musicas',
            },
        ),
    ]
