# Generated by Django 3.2.7 on 2021-09-27 18:21

import display.models.musica
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20210924_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='url',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='musica',
            field=models.FileField(blank=True, help_text='Adicione aqui musicas no formato .mp3', null=True, upload_to='musics/', validators=[display.models.musica.Musica.validate_file_extension], verbose_name='Musica'),
        ),
    ]
